\connect curator_database;

INSERT INTO curator_schema.art_table (title, characters, artist, width, height, framed, primary_color, file, notes) VALUES
('Stephanie Brown Robin','Robin','Dean Trippe',10,8,'Y','Orange','IMG_9420.JPG','Signed, Sketch'),
('Shall not pass','LotR','Sscott Maynard',11,8.5,'N','x','IMG_9443.JPG','Comic strip'),
('X-men Stainglass','X-men','Chris Davenport',11,9,'N','Orange, blue','IMG_9444.JPG','x'),
('Mjolnir Hugs','Thor','?',8,10,'N','White, light','IMG_9431.JPG','Signed'),
('Miles and Luna','Spider-man, Moongirl','?',8.5,11,'N','B/W','IMG_9435.JPG','Signed,Original'),
('Sleep over','Toothless, Stitch','?',17,11,'N','Warm, Black, Blue','IMG_9432.JPG','x'),
('Jurassic Park Quotes','Multi','DAP',18,12,'Y','Purple, Green','IMG_9427.JPG','Signed'),
('Lego Hulkbuster','Ironman','Ron Lim',10,13,'N','Red','IMG_9436.JPG','Hulkbuster Purchase'),
('Lego Hulkbuster','Ironman','Ron Lim',10,13,'N','B/W','IMG_9437.JPG','Lego VIP'),
('Lego Captain Marvel','Captain Marvel, Nick Fury, Goose','Ron Lim','10','13','N','Red, Blue','x','Lego VIP'),
('OG Team','Avengers','Michael Cho',19,13,'Y','Blue','IMG_9428.JPG','Signed'),
('X-Men','X-men','Simone Bianchi',17,13.5,'N','Blue','IMG_9450.JPG','x'),
('Stan Lee','Stan Lee','David Colwer(?)',11,14,'N','Purple, Red','IMG_9438.JPG','x'),
('Guitar Serenade','Batman, Catwoman','?',12,16,'Y','Black','IMG_9421.JPG','Signed'),
('Justice League','Team','Michael Cho',13,16.25,'N','x','IMG_9430.JPG','Signed'),
('Marvel Comics','Spider-man','Paulo Rivera',11,17,'Y','Grey, Red, Black','IMG_9419.JPG','Signed'),
('Sunflower Boy','x','Ashwara',11,17,'Y','Blue, yellow','IMG_9423.JPG','x'),
('Young Justice','Team','Todd Nauck',11,17,'Y','Orange, Red','IMG_9425.JPG','Signed'),
('Marvel Arm Wrestling','Ironman, She-Hulk','Amanda Conner',11,17,'Y','Black, Green, Red','IMG_9426.JPG','Signed'),
('Amazing Spider-man','Spider-man','Michael Cho',11,17,'N','Red','IMG_9429.JPG','Signed'),
('Isla Nublar Map','Jurassic Park','?',11,17,'N','Blue','IMG_9433.JPG','Signed'),
('CBLDF Member Poster','Madman','Alfred Allred',11,17,'N','Blue','IMG_9440.JPG','x'),
('Spider-man Homecoming','Spider-man','?',11,17,'N','Blue','IMG_9441.JPG','Cinmark Exclusive'),
('Burger of the Day','Bob''s Burgers','Andrew Heath',11,17,'N','Yellow','IMG_9442.JPG','x'),
('Street Heros','Spider-man, Punisher, Daredevil, Wolverine','Romitas',11,17,'N','B/W','IMG_9446.JPG','x'),
('Noir','Spider-man Noir','DG',11,17,'N','B/W','IMG_9447.JPG','Signed'),
('Kirkman Heroes','Invincible, Brit, TechJacket','Ryan Ottley',11,17,'N','Orange-Red','IMG_9448.JPG','Signed (lower left)'),
('Wasp up!','Spider-man','Billy Tan',12,18,'N','Blue','IMG_9449.JPG','Signed'),
('Apollo 11','x','Thomas J. ROmer',36,18,'N','Black, Orange','IMG_0725.jpg','chopshopstore.com'),
('International Space Station','x','Thomas J. ROmer',36,18,'N','Black, Blue','IMG_0726.jpg','chopshopstore.com'),
('Toronoto Guests of Honor','Grendel, SIP, Mage','Terry Moore, Matt Wagner, Marv Wolfman',13,19,'N','Blue','IMG_9451.JPG','Signed (all three)'),
('Pale Blue Dot','Carl Sagan','?',17,22,'N','Blue, Black','IMG_0724.jpg','chopshopstore.com'),
('Get Up Kids Tour','Get Up Kids','?',16,23,'Y','Blue','x','x'),
('Spider-man Eyes','Spider-man','?',16.25,23,'Y','Red','IMG_9417.JPG','Minimalist'),
('Penny Arcade Beach','Penny Arcade','Mike Krahulik',17,23,'Y','Blue','x','Signed (w/ Scott Kurtz)'),
('Zoidberg','Zoidberg','DAP',12,24,'N','Orange','IMG_9434.JPG','Signed'),
('Sky Riders','x','Karen Dupree',18,24,'Y','Yellow','IMG_9418.JPG','x'),
('Generation','Starman','Tony Harris',18,24,'N','Orange','IMG_9445.JPG','Signed, 28/50, Baltimore' );